### ISSUE TITLE
Google Drive API authentication  didn't create token.pickle 

### ISSUE THREAD

**Issue by mwaseemwali** [googleapis/google-api-python-client#622] opened 2019-02-06 07:56 UTC
i use Google Drive Api  Quick Start. and code  as given in google example.
when i system start authentication it takes too much time and at the end show http:/localhost:8080 error page
.

code is
 SCOPES = ['https://www.googleapis.com/auth/drive.file']
    creds = None
    # The file token.pickle stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    os.path
    if os.path.exists('token.pickle'):
      with open('token.pickle', 'rb') as token:
        creds = pickle.load(token)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
      if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
      else:
        flow = InstalledAppFlow.from_client_secrets_file('credentials.json', SCOPES)
        #flow = InstalledAppFlow.from_client_secrets_file('client_id.json', SCOPES)
        creds = flow.run_local_server() 

**system didn't create token.pickle file , any help**

**Comment by mosesokemwa** [comment] 2019-02-12 07:33
You were on the right path and as far as I can tell your code is working. The missing step of the code is to save the ``creds`` in `token.pickle` file. Refer to this [example](https://developers.google.com/gmail/api/quickstart/python) in the Python quickstart doc.

Short version, you need to add the following at the end of you code

```python
# Save the credentials for the next run
        with open('token.pickle', 'wb') as token:
            pickle.dump(creds, token)
```

**Comment by mwaseemwali** [comment] 2019-02-12 12:48
that actual problem. token.pickle not saved. i try again and again, in 40th
attempt it creates.
i want to know , why it happened.

**Comment by mosesokemwa** [comment] 2019-02-18 11:29
I can't be certain why that happened without a way of recreating the error.

**Comment by james7mac** [comment] 2019-04-03 09:52
Hey im having this same issue trying to get quickstart to work with google sheets.

I'm a rookie but i have noticed some strange behavior that i think is related to having sabNZBD operating on localhost:8080

do you have anything using localhost:8080 ?

**Comment by james7mac** [comment] 2019-04-03 10:11
Confirmed! I changed sabNZBD's operating port from 8080 to 8081 and the problem was resolved!

Note: shutting down the sabnzbd didnt fix the issue, i had to change the port for it to be resolved.

If you have any software using port 8080 i suggest changing it so that port 8080 is clear

**Comment by busunkim96** [comment] 2019-04-03 19:08
It's possible to specify the operating host and port when using `.run_local_server`. The host defaults to 'localhost' and the port '8080'.

```
creds = flow.run_local_server(port='8081')   # set local to port 8081
```
https://google-auth-oauthlib.readthedocs.io/en/latest/reference/google_auth_oauthlib.flow.html#google_auth_oauthlib.flow.InstalledAppFlow.run_local_server

**Comment by busunkim96** [comment] 2019-04-03 19:09
I am going to close this issue now, please let us know if you are still experiencing issues.

**Closed by busunkim96** 2019-04-03 19:09 UTC
Labels: type: question
