### ISSUE TITLE
Play Developer Reporting API - UnknownApiNameOrVersion

### ISSUE THREAD

**Issue by schunlee** [googleapis/google-api-python-client#1798] opened 2022-05-13 04:24 UTC
```
SCOPE = ("https://www.googleapis.com/auth/playdeveloperreporting",)
credentials = service_account.Credentials.from_service_account_info(json.loads(credential_json))
scoped_credentials = credentials.with_scopes(SCOPE)
build("playdeveloperreporting", "v1alpha", credentials=scoped_credentials)
```
* google-api-python-client 2.47.0
* get an error -> googleapiclient.errors.UnknownApiNameOrVersion: name: playdeveloperreporting  version: v1alpha
* from Discovery document api, I can see playdeveloperreporting and v1alpha
```
{'kind': 'discovery#directoryItem', 
'id': 'playdeveloperreporting:v1alpha1', 
'name': 'playdeveloperreporting', 
'version': 'v1alpha1', 
'title': 'Google Play Developer Reporting API', 
'description': '', 
'discoveryRestUrl': 'https://playdeveloperreporting.googleapis.com/$discovery/rest?version=v1alpha1', 
'icons': {'x16': 'https://www.gstatic.com/images/branding/product/1x/googleg_16dp.png', 
'x32': 'https://www.gstatic.com/images/branding/product/1x/googleg_32dp.png'}, 
'documentationLink': 'https://developers.google.com/play/developer/reporting', 
'preferred': False}
```

**Comment by parthea** [comment] 2022-05-17 12:55
Hi @schunlee,

I was able to reproduce the issue locally. I found the issue is that the version `v1alpha` should be `v1alpha1`. Please could you try again using the following?

```
from googleapiclient.discovery import build
build("playdeveloperreporting", "v1alpha1")
```

**Comment by parthea** [comment] 2022-05-17 12:55
I'm going to close this issue but please feel free to re-open it if you have additional questions.

**Closed by parthea** 2022-05-17 12:55 UTC
Labels: type: question, api:playdeveloperreporting

**Comment by dendihandian** [comment] 2023-10-05 09:28
@parthea Hi Anthonios, also @schunlee 

Does this client package (playdeveloperreporting) able to ingest reporting/statistics and reviews/rate data of my android app?
