### ISSUE TITLE
requests dont respect CLOUDSDK_CORE_CUSTOM_CA_CERTS_FILE, causing ssl errors

### ISSUE THREAD

**Issue by marengaz** [googleapis/google-api-python-client#1775] opened 2022-04-25 17:24 UTC
hi all

i am trying to use this api behind zscaler.

gcloud run services list works
other python gcp apis (bigquery, data catalog, ...) work in this venv
i have set these env vars:
CURL_CA_BUNDLE=/Users/ben.marengo/certifi-zscaler-ca-bundle.pem
CLOUDSDK_CORE_CUSTOM_CA_CERTS_FILE=/Users/ben.marengo/certifi-zscaler-ca-bundle.pem
SSL_CERT_FILE=/Users/ben.marengo/certifi-zscaler-ca-bundle.pem

is there extra config i need to set up somewhere?

thanks

#### Environment details

  - OS type and version: macos 12.2.1
  - Python version: `Python 3.9.5`
  - pip version: `pip 22.0.3 from /Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/pip (python 3.9)`
  - `google-api-python-client` version: `google-api-python-client==2.45.0`

#### Code example

```python 
import google
import googleapiclient.discovery


proj = 'my-project'
region = 'europe-west2'

credentials, _ = google.auth.default()

service = googleapiclient.discovery.build("run", "v2", credentials=credentials, cache_discovery=False)
req = service.projects().locations().services().list(parent=f"projects/{proj}/locations/{region}")
resp = req.execute()
```

#### Stack trace
```
/Users/ben.marengo/code/pyenvs/scratch/bin/python /Users/ben.marengo/code/scratch/cloud_run.py
Traceback (most recent call last):
  File "/Users/ben.marengo/code/scratch/cloud_run.py", line 11, in <module>
    resp = req.execute()
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/googleapiclient/http.py", line 922, in execute
    resp, content = _retry_request(
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/googleapiclient/http.py", line 221, in _retry_request
    raise exception
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/googleapiclient/http.py", line 190, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/google_auth_httplib2.py", line 209, in request
    self.credentials.before_request(self._request, method, uri, request_headers)
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/google/auth/credentials.py", line 133, in before_request
    self.refresh(request)
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/google/oauth2/credentials.py", line 302, in refresh
    ) = reauth.refresh_grant(
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/google/oauth2/reauth.py", line 322, in refresh_grant
    response_status_ok, response_data = _client._token_endpoint_request_no_throw(
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/google/oauth2/_client.py", line 115, in _token_endpoint_request_no_throw
    response = request(method="POST", url=token_uri, headers=headers, body=body)
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/google_auth_httplib2.py", line 119, in __call__
    response, data = self.http.request(
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/httplib2/__init__.py", line 1725, in request
    (response, content) = self._request(
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/httplib2/__init__.py", line 1441, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/httplib2/__init__.py", line 1363, in _conn_request
    conn.connect()
  File "/Users/ben.marengo/code/pyenvs/scratch/lib/python3.9/site-packages/httplib2/__init__.py", line 1155, in connect
    self.sock = self._context.wrap_socket(sock, server_hostname=self.host)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

Process finished with exit code 1

```

**Comment by marengaz** [comment] 2022-04-28 14:26
setting env `HTTPLIB2_CA_CERTS=/Users/ben.marengo/certifi-zscaler-ca-bundle.pem` seems to be a good workaround for now
https://github.com/httplib2/httplib2/blob/master/python3/httplib2/certs.py#L28

**Comment by parthea** [comment] 2022-04-29 14:22
Hi @marengaz ,
I'm glad that you found a workaround! I also found a related issue here: https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/issues/166.

I'm going to close this issue as I'm not able to reproduce it but please feel free to re-open it if you have additional questions.

**Closed** 2022-04-29 14:23 UTC
Labels: type: question
