### ISSUE TITLE
GMail batch path incorrect warning

### ISSUE THREAD

**Issue by thehesiod** [googleapis/google-api-python-client#859] opened 2020-04-11 09:53 UTC
#### Environment details

  - OS: OSX/linux
  - Python version: 3.8
  - pip version:
  - `google-api-python-client` version: latest

#### Steps to reproduce

  1. call gmail batch endpoint via `new_batch_http_request`

You'll get the warning about `You have constructed a BatchHttpRequest using the legacy batch endpoint https://www.googleapis.com/batch. This endpoint will be turned down on March 25, 2019`

The problem is that for the gmail endpoint this is the endpoint from the discovery doc.  The Gmail discovery doc's relevant portions look like this:

```
 'rootUrl' = {str} 'https://www.googleapis.com/'
 'batchPath' = {str} 'batch'
```

so seems like the warning is wrong for gmail.

**Comment by busunkim96** [comment] 2020-04-13 17:07
```
"rootUrl": "https://www.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "gmail",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "batchPath": "batch",
```

Confirmed by checking https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest.

It would be possible to add some sort of manual logic to check that the path isn't coming directly from the discovery doc. 

Interestingly, this is the only API I know of with a generic rootUrl (www.googleapis.com) and a generic batchPath (batch). I'm doing some investigation to see if this is intended.

**Comment by jay0lee** [comment] 2020-05-23 14:10
Seems like this was fixed at some point, I can't reproduce it:

```
$ curl https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest --compressed -s | python3 -c "import json, sys; disc=json.load(sys.stdin); print(disc['rootUrl'], disc['batchPath']);"
https://www.googleapis.com/ batch/gmail/v1
```

**Comment by mik-laj** [comment] 2020-05-23 15:30
Affirmative. This document was fixed 20 days ago.
https://github.com/mik-laj/discovery-api/commit/91147f5c708be5e65ac3528ba8e9beff32daf93e

**Comment by mik-laj** [comment] 2020-05-23 15:35
This problem still exists in the following API:
```
gamesConfiguration:v1configuration
gamesManagement:v1management
oauth2:v2
tagmanager:v2
tasks:v1
toolresults:v1beta3
```

**Comment by thehesiod** [comment] 2020-05-23 22:13
cool, should I close this then?

btw `jq` tip: 
```bash
curl -s https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest | jq '.rootUrl + .batchPath'
```
results with
```
"https://www.googleapis.com/batch/gmail/v1"
```
:)

**Comment by busunkim96** [comment] 2020-05-26 17:27
Ah good to know. I'll close this issue, and we can keep an eye on the remaining APIs.

**Closed by busunkim96** 2020-05-26 17:27 UTC
Labels: api: gmail, type: cleanup
