### ISSUE TITLE
Google Keep API: `notes().create()` error message too vague

### ISSUE THREAD

**Issue by SkyeChen-28** [googleapis/google-api-python-client#2236] opened 2023-09-15 01:50 UTC
I'm trying to create a Keep note using the Google API Python client, but I keep getting a very vague error message:

```
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://keep.googleapis.com/v1/notes?alt=json returned "Request contains an invalid argument.". Details: "Request contains an invalid argument.">
```

I'm pretty sure I've authenticated correctly since calling notes().list().execute() returns an empty dict instead of an authentication error message. 

I'm making Notes by following the dict format as specified here: https://googleapis.github.io/google-api-python-client/docs/dyn/keep_v1.notes.html#create

This is the note I'm trying to create:
```{python}
    test_note3 = {  # A single note.
        "body": {  # The content of the note. # The body of the note.
            "text": {  # The block of text for a single text section or list item. # Used if this section's content is a block of text. The length of the text content must be less than 20,000 characters.
                "text": "a",  # The text of the note. The limits on this vary with the specific field using this type.
            },
        },
        "title": "A String",  # The title of the note. Length must be less than 1,000 characters.
    }
```

I execute the following code:
```{python}
with build("keep", "v1", credentials=credentials) as service:
    service.notes().create(body=test_note3).execute()
```

and I get the error message I mentioned earlier:
```
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://keep.googleapis.com/v1/notes?alt=json returned "Request contains an invalid argument.". Details: "Request contains an invalid argument.">
```

If I slightly alter the dict I input, I get more helpful error messages. For example:
1. If I leave the text field empty...
```{python}
    test_note3 = {  # A single note.
        "body": {  # The content of the note. # The body of the note.
            "text": {  # The block of text for a single text section or list item. # Used if this section's content is a block of text. The length of the text content must be less than 20,000 characters.
                "text": "",  # The text of the note. The limits on this vary with the specific field using this type.
            },
        },
        "title": "A String",  # The title of the note. Length must be less than 1,000 characters.
    }
```
...that yields this error:
```
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://keep.googleapis.com/v1/notes?alt=json returned "Request contains an invalid argument.". Details: "[{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'note.body.text', 'description': 'Note contains an empty text content.'}]}]">
```
2. If I forget the second subtext field...
```{python}
    test_note3 = {  # A single note.
        "body": {  # The content of the note. # The body of the note.
                "text": "a",  # The text of the note. The limits on this vary with the specific field using this type.
        },
        "title": "A String",  # The title of the note. Length must be less than 1,000 characters.
    }
```
...I get this error:
```
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://keep.googleapis.com/v1/notes?alt=json returned "Invalid value at 'note.body.text' (type.googleapis.com/google.apps.keep.v1.TextContent), "a"". Details: "[{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'note.body.text', 'description': 'Invalid value at \'note.body.text\' (type.googleapis.com/google.apps.keep.v1.TextContent), "a"'}]}]">
```
3. If I misspell the field...
```{python}
    test_note3 = {  # A single note.
        "body": {  # The content of the note. # The body of the note.
            "text": {  # The block of text for a single text section or list item. # Used if this section's content is a block of text. The length of the text content must be less than 20,000 characters.
                "Text": "a",  # The text of the note. The limits on this vary with the specific field using this type.
            },
        },
        "title": "A String",  # The title of the note. Length must be less than 1,000 characters.
    }
```
...I get this error:
```
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://keep.googleapis.com/v1/notes?alt=json returned "Invalid JSON payload received. Unknown name "Text" at 'note.body.text': Cannot find field.". Details: "[{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'note.body.text', 'description': 'Invalid JSON payload received. Unknown name "Text" at \'note.body.text\': Cannot find field.'}]}]">
```

Am I just formatting the dict incorrectly? or is there an issue with this package parsing Python dicts for Notes? why is the error message so unhelpful when I follow the provided template correctly (as far as I can tell).

**Comment by altostratous** [comment] 2023-10-29 01:25
Same issue here.

**Comment by corte** [comment] 2023-10-31 10:20
Same here. I think the problem is with keep API and not the python package.
If I just extract the token from the credentials with
```python
credentials.token
```
And try the same request in Postman, I get the same vague error:
![image](https://github.com/googleapis/google-api-python-client/assets/4606160/71a79517-892e-4171-9135-14f2663fb264)

**Comment by ohmayr** [comment] 2024-01-16 09:55
This error is thrown by the Keep API and is not related to the python library. If you'd like the message to be more informative, You can report this issue directly on the [Keep API](https://developers.google.com/keep/api/reference/rest/v1/notes/create) reference page by clicking on `Send Feedback`.

**Comment by parthea** [comment] 2024-01-26 16:59
I'm going to close this issue as it is related to the API rather than the client library. Please [use this link](https://developers.google.com/keep/api/support#developer_product_feedback) to send feedback about the API.

**Closed by parthea** 2024-01-26 16:59 UTC
