### ISSUE TITLE
how to download folder from google drive?

### ISSUE THREAD

**Issue by EhtishamSabir** [googleapis/google-api-python-client#1399] opened 2021-06-05 00:42 UTC
worst documentation of google drive first of all & secondly where are the sample code for python?

**Comment by parthea** [comment] 2021-06-06 07:41
Hi @EhtishamSabir, 

We have samples for Google Drive [here](https://developers.google.com/drive/api/v3/quickstart/python) and [here](https://github.com/googleworkspace/python-samples/tree/master/drive) however users have mentioned in https://github.com/googleapis/google-api-python-client/issues/531 that this documentation needs improvement. Please update https://github.com/googleapis/google-api-python-client/issues/531 which is linked to internal bug trackers if you have additional feedback for the Google Drive Samples. I'm going to close this issue as a duplicate of #531.  I'm going to update https://github.com/googleapis/google-api-python-client/issues/531 once I have an ETA from the team working on the samples. 

Googlers see b/190226456 and b/185393300 for updates.

**Closed by parthea** 2021-06-06 07:41 UTC
Labels: api: drive, type: question

**Comment by EhtishamSabir** [comment] 2021-06-29 14:09
Here there is no documentation on using pickel file for saving session. because user can't manually confirm authorization each time.

Sorry I was angry after doing lot's of searching. but please guys update documentation otherwise AWS is going to lead in next few years :)


        # Check if file token.pickle exists
        if os.path.exists('token.pickle'):
            # Read the token from the file and
            # store it in the variable self.creds
            with open('token.pickle', 'rb') as token:
                self.creds = pickle.load(token)

        # If no valid credentials are available,
        # request the user to log in.
        if not self.creds or not self.creds.valid:

            # If token is expired, it will be refreshed,
            # else, we will request a new one.
            if self.creds and self.creds.expired and self.creds.refresh_token:
                self.creds.refresh(Request())
            else:
                flow = InstalledAppFlow.from_client_secrets_file(
                    'credentials.json', SCOPES)
                self.creds = flow.run_local_server(port=0)

            # Save the access token in token.pickle
            # file for future usage
            with open('token.pickle', 'wb') as token:
                pickle.dump(self.creds, token)
