### ISSUE TITLE
Dialogflow API does not appear to work via discovery-based clients

### ISSUE THREAD

**Issue by jceresini** [googleapis/google-api-python-client#1274] opened 2021-03-30 20:39 UTC
When attempting to use the dialogflow API to list agents (https://googleapis.github.io/google-api-python-client/docs/dyn/dialogflow_v3.projects.locations.agents.html#list) I get a 400 back from the API. It looks like the dialogflow v3 API has location-specific endpoints.

# Example code
```
from googleapiclient.discovery import build

client = build('dialogflow', 'v3')
service = client.projects().locations().agents()
agents = service.list(parent='projects/my-project/locations/us-east1').execute()
```

# Output (exception)
```
$ python dialogflow-discovery.py
Traceback (most recent call last):
  File "dialogflow-discovery.py", line 5, in <module>
    agents = service.list(parent='projects/my-project/locations/us-east1').execute()
  File "/Users/jceresini/venvs/resource-policy-evaluation-library/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/jceresini/venvs/resource-policy-evaluation-library/lib/python3.7/site-packages/googleapiclient/http.py", line 920, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://dialogflow.googleapis.com/v3/projects/my-project/locations/us-east1/agents?alt=json returned "Dialogflow server in 'us' received request for resources located in 'us-east1.'". Details: "Dialogflow server in 'us' received request for resources located in 'us-east1.'">
```

**Comment by busunkim96** [comment] 2021-03-31 14:44
This seems to be expected behavior for the Dialogflow API. See https://cloud.google.com/dialogflow/es/docs/how/region.

It looks like for US the only supported region is `us`.

![image](https://user-images.githubusercontent.com/8822365/113162918-ec77ea80-91fc-11eb-95b8-cccd5ba1dd38.png)


```py
from googleapiclient.discovery import build

client = build('dialogflow', 'v3')
service = client.projects().locations().agents()
agents = service.list(parent='projects/my-project/locations/us').execute()
```

If you are able, please use `google-cloud-dialogflow` instead of the discovery client. The samples on cloud.google.com are written for `google-cloud-dialogflow`.

**Comment by jceresini** [comment] 2021-03-31 16:24
I currently have an agent in us-east1. If i query with `parent='projects/my-project/locations/us'` I get 0 results.

I managed to get it working by doing the following:

```
from googleapiclient.discovery import build

opts = ClientOptions(api_endpoint=f'https://us-east1-dialogflow.googleapis.com/')
client = build('dialogflow', 'v3', client_options=opts)
service = client.projects().locations().agents()
agents = service.list(parent='projects/my-project/locations/us-east1').execute()
```

We prefer to use the discovery clients because we interact with a large number of google APIs and the consistent client structure makes it really easy to add support for new apis/resources.

**Comment by parthea** [comment] 2021-08-11 11:27
I'm going to close this issue as resolved but please feel free to re-open it if I've missed any outstanding items.

**Closed by parthea** 2021-08-11 11:27 UTC
Labels: type: question
