### ISSUE TITLE
Discovery base url inconsistent in some cases

### ISSUE THREAD

**Issue by jceresini** [googleapis/google-api-python-client#665] opened 2019-05-21 17:47 UTC
Sometimes the baseUrl for the compute api is returned as `www.googleapis.com/compute`, other times I see `compute.googleapis.com/compute`. The code this is affecting for me determines if the api is in the hostname, or the first segment of the URL, but doesn't expect it to be both. I think latter result mentioned above is incorrect. 

I reference the script, and a link to the inconsistent results below, but ill also include the example output here directly:

```
$ python test.py
https://compute.googleapis.com/compute/v1/projects/
https://www.googleapis.com/compute/v1/projects/
https://www.googleapis.com/compute/v1/projects/
https://compute.googleapis.com/compute/v1/projects/
```
This looks like it would be an issue in the discovery API itself, but I'm not sure how to submit a bug for that. If there's nothing that can be done, this can be closed, but I wanted to report it in case someone else encounters it.

#### Environment details

  - OS: N/A
  - Python version: replicated in 3.4, 3.5, 3.6, 3.7 
  - pip version:
  - `google-api-python-client` version: 1.7.8

#### Steps to reproduce

  1. Run the simple script here: https://github.com/jceresini/test-gcp-discovery/blob/master/test.py
  2. Example output here: https://travis-ci.com/jceresini/test-gcp-discovery/jobs/201917796#L238

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by jceresini** [comment] 2019-05-21 18:05
Just to provide more info, we noticed this while attempting to generate a [full resource name](https://cloud.google.com/apis/design/resource_names#full_resource_name) using the request URL using the google-api-python-client library. That code is open sourced: https://github.com/forseti-security/resource-policy-evaluation-library/blob/master/rpe/resources/gcp.py#L116

I realize its an odd use-case for this library. But anyway, we noticed our test cases failing _occasionally_, so far only for the compute API.

**Comment by busunkim96** [comment] 2019-05-21 18:06
@jceresini Thank you for the report and the sample scripts! We'll investigate to see if this is something odd happening in the discovery document or in the way we build the url.

**Comment by busunkim96** [comment] 2019-05-21 20:13
It looks like we're in the process of rolling out a change to the baseUrl for some of our APIs (including compute). Both those URLs are correct (we're moving from the `www.googleapis.com/compute/v1/projects` to `compute.googleapis.com/compute/v1/projects`. 

This is working as intended, so I will close the issue. It looks like you already have a workaround for determining the full resource name. Let us know if you have any other issues!

**Closed by busunkim96** 2019-05-21 20:13 UTC
Labels: priority: p2, status: investigating, type: bug

**Comment by jceresini** [comment] 2019-05-21 20:53
Every other api I've run into uses one of these 2 format:

`www.googleapis.com/[api_name]/[version]`
`[api_name]'.googleapis.com/[version]`

This is the first I've seen that is a combination of the 2. Its not an issue with this library though, so I submitted some feedback in the compute issuetracker: https://issuetracker.google.com/issues/133249122

Thanks for looking into it!
