### ISSUE TITLE
instanceGroupManagers can not insert a multi-zone instance group

### ISSUE THREAD

**Issue by wavenator** [googleapis/google-api-python-client#400] opened 2017-05-16 17:51 UTC
`compute.instanceGroupManagers().insert` does not accept a region in its `zone` input parameter, nor accepts a `region` parameter.
I know it is a new feature in Google Cloud instance groups so it is probably in progress.

Thanks!

**Comment by antoniomika** [comment] 2018-06-04 21:03
Ran into a similar issue with this, putting this here for the next person that comes looking: 

You need to use the `regionInstanceGroupManagers()` resource instead of `instanceGroupManagers()`. More information available here: https://developers.google.com/resources/api-libraries/documentation/compute/v1/python/latest/compute_v1.regionInstanceGroupManagers.html#insert .

**Comment by mcdonc** [comment] 2018-07-24 17:53
I'm assigning this to @crwilcox provisionally because I don't believe I can use this API without some administrative help from a Googler.

**Comment by crwilcox** [comment] 2018-08-16 19:36
Thank you @antoniomika for your assistance. That is correct. For regionally scoped managers, you need to use `regionInstanceGroupManager`

@mcdonc , I think this may be something we can fix with better documentation perhaps. By design, `instanceGroupManagers` are not scoped to regions. 
Perhaps if we added a mention of `regionInstanceGroupManagers` in https://developers.google.com/resources/api-libraries/documentation/compute/v1/python/latest/compute_v1.instanceGroupManagers.html#insert ?

**Closed** 2018-12-04 22:48 UTC
Labels: status: blocked, type: question
