### ISSUE TITLE
Docs for Google Drive API need update, and more examples.

### ISSUE THREAD

**Issue by troymaclure** [googleapis/google-api-python-client#531] opened 2018-06-19 18:30 UTC
To make it short, the doc in python for the version 3 of the API, at least regarding Google Drive, is lacking. The same apply for other langages. 

There is 1 example on github, from 2012, for the API v2, and that's it. The only update was for a typo in the readme.

The official doc in google developer pages for V3 doesn't say much despite the number of pages and is lacking example too. You have to look at V2 API to get approximative code which return errors and need a few changes to work. 

All in all, You have to put little inconsistent pieces of code from here and there one after another to figure out how it works, even for basic operation like uploading a file.

To resume this rant, the current official doc is poorly designed, doesn't help much and need more exhaustive examples and updated codes.

**Comment by grant** [comment] 2018-08-21 07:16
@stephanepiriou Can you be specific with what changes you're looking for?

We unfortunately, haven't migrated the Drive API code from developers.google.com to GitHub yet. Some upload samples for python are here:
https://developers.google.com/drive/api/v3/manage-uploads

Please state 1-2 specific things you want added or changed.

**Comment by vsoch** [comment] 2018-11-03 03:48
I'd like to see:

 - full import statements for modules required. For example, the download file page Python references a `MediaIoBaseDownload` but I don't know what that is.
 - A full example of starting from creating a client to downloading a file, downloading a version, and saving. It's not completely straightforward to a new user that there are several different versions or even modules to use here.
 - A better description for the output - a stream into bytes is different from into a file, for example.

Thanks muchly! :)

**Comment by keni7385** [comment] 2018-12-18 07:51
I would like to see also an example of updating a file

**Comment by fhinkel** [comment] 2020-12-07 21:00
Greetings, we're closing this due to inactivity. Please let us know if the issue needs to be reopened.

**Comment by vsoch** [comment] 2020-12-07 21:56
I think this issue needs to be reopened - I don't see any of the changes reflected in the Drive API -> https://developers.google.com/drive/api/v3/quickstart/python. As we aren't Google employees, we are not empowered to do a PR or similar, so I'm not sure how there is expected to be any activity?

**Comment by vsoch** [comment] 2020-12-07 22:27
Thanks!

**Comment by Uttkarsh09** [comment] 2021-05-28 19:05
PLEASE add more examples for different operations..... : (

**Comment by parthea** [comment] 2021-06-06 07:29
Hi @Uttkarsh09, I'll update this thread once I have an ETA from the team working on the Google Drive Samples. Googlers see b/190226456 and b/185393300 for updates.

**Comment by FirefighterBlu3** [comment] 2022-04-01 18:52
It's 2022, four years later and the documentation and repo for v3 still don't have any code samples for most [all?] things. Things that ought to work raise or return errors. e.g. _service = build('permissions', 'v3', credentials=creds)_ raises _googleapiclient.errors.UnknownApiNameOrVersion: name: permissions  version: v3_ 

The only documentation for these are HTTP methods.

Please update the documentation with code samples and put code samples in the repo.

**Comment by parthea** [comment] 2022-06-24 17:17
The samples for Google Drive live in a different repository : https://github.com/googleworkspace/python-samples

I'm going to close this issue as a duplicate of https://github.com/googleworkspace/python-samples/issues/237.

If you encounter an issue with google-api-python-client, please [click here](https://github.com/googleapis/google-api-python-client/issues/new/choose) to open a new issue. If you'd like to follow up on samples for Google Drive v3, please add a comment to [this issue](https://github.com/googleworkspace/python-samples/issues/237).

**Closed by parthea** 2022-06-24 17:17 UTC
Labels: type: docs, api: drive
