### ISSUE TITLE
Invalid argument "eventType" for search request

### ISSUE THREAD

**Issue by greenSkin** [googleapis/google-api-python-client#2395] opened 2024-05-09 16:23 UTC
Trying to set [eventType](https://developers.google.com/youtube/v3/docs/search/list#eventType) on search request fails with a "Request contains an invalid argument." Removing the `eventType` parameter otherwise results in a successful response.

#### Environment details

  - OS type and version: macOS 14.4.1
  - Python version: 3.11.7
  - pip version: 24.0
  - `google-api-python-client` version: 2.128.0

#### Steps to reproduce

  1. Make a search request with the eventType parameter.

#### Code example

```python
request = youtube.search().list(part="snippet", forMine=True, maxResults=max_results, order="date", type="video", eventType="live")
```

#### Stack trace
```
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://youtube.googleapis.com/youtube/v3/search?part=snippet&forMine=true&maxResults=30&order=date&type=video&eventType=live&alt=json returned "Request contains an invalid argument.". Details: "[{'message': 'Request contains an invalid argument.', 'domain': 'global', 'reason': 'badRequest'}]">
```

**Comment by ohmayr** [comment] 2024-05-10 19:13
@greenSkin The behaviour of the client is consistent with the underlying API. You can verify this by making the API call using the API explorer [here](https://developers.google.com/youtube/v3/docs/search/list?apix_params=%7B%22part%22%3A%5B%22snippet%22%5D%2C%22eventType%22%3A%22live%22%2C%22forMine%22%3Atrue%2C%22order%22%3A%22date%22%2C%22type%22%3A%5B%22video%22%5D%7D#eventType).

If you believe this is a bug, kindly report it directly to the `Youtube API Service` team via the Issue Tracker at the bottom of the above link.

Closing this since the issue is observed in the underlying API. Feel free to open another issue if you have concerns with the python client.

**Closed by ohmayr** 2024-05-10 19:13 UTC
