### ISSUE TITLE
Directory API and mail sender encoding

### ISSUE THREAD

**Issue by jberthet** [googleapis/google-api-python-client#356] opened 2017-02-28 13:19 UTC
Hello,

I have a issue with the Directory API and the resulting user record on Google's servers.

I use the API for user account provisioning. Every string sent to the API in the Python code is UTF-8 encoded.

The issue arise when a user try to use GMail service with his account. The name for the mail sender appears with fancy characters instead of accents, both on the web UI for sending the mail and on the mail receiver side.

I had some exchange with Google Suite support. They says that the problem occurs because the name is encoded with "UTF8 Base64" instead of "UTF8 Quoted Printable" on their server and that I should set "UTF8 Quoted Printable" when using API and said me to see with Python API support.

I couldn't find how to do this on the Directory API documentation, and since the Python support group is closed, I open up the issue here.

Any help would be appreciated on how to force Quoted Printable encoding when using the Python Directory API.

Regards.

**Comment by lukesneeringer** [comment] 2017-03-23 19:40
Hi @jberthet,
Have GSuite support followed up with you on this? I am not sure what this refers to,  but they should be able to help you.

**Comment by jberthet** [comment] 2017-03-24 10:57
Hi,

The fact is GSuite sent us here. They said they cannot help us and that the encoding problem came from the Python API.

Regards.

**Comment by lukesneeringer** [comment] 2017-03-24 15:27
Ah, okay. Can you show the code that you are using so we can try to reproduce? Right now it is unclear to me.

**Comment by mcdonc** [comment] 2018-07-27 13:21
I do not have G-Suite access yet, so provisionally assigning this to @crwilcox.

**Comment by fhinkel** [comment] 2020-12-07 21:01
Greetings, we're closing this due to inactivity. Please let us know if the issue needs to be reopened.

**Closed by fhinkel** 2020-12-07 21:01 UTC
Labels: status: blocked, type: question
