### ISSUE TITLE
Unable to grant owner access to User members

### ISSUE THREAD

**Issue by rohithmn3** [googleapis/google-api-python-client#537] opened 2018-07-04 08:15 UTC
I couldn't able to add new member in GCP(iam) with the role owner using the gcloud command The below command fails:
`gcloud projects add-iam-policy-binding linuxacademy-3 --member user:rohithmn3@gmail.com --role roles/owner`

With the below Error:
```
ERROR: (gcloud.projects.add-iam-policy-binding) INVALID_ARGUMENT: Request contains an invalid argument.
- '@type': type.googleapis.com/google.cloudresourcemanager.v1.ProjectIamPolicyError
  member: user:rohithmn3@gmail.com
  role: roles/owner
  type: SOLO_MUST_INVITE_OWNERS
```
But, the same command works well for other roles like: viewer, browser...! It just doesn't work for "owner". Is there any alternative for this; if yes, How to add this in my Python Code. Please help me here..!

Thank you!

Regards, 
Rohith

**Comment by mcdonc** [comment] 2018-07-05 03:01
Awaiting credentials from Google for GSuite so I can confirm the issue.

**Comment by scottpazelt** [comment] 2018-07-13 10:18
Experiencing the same issue assigning role\owner. Please advise if a workaround is available.

Thanks.

**Comment by mcdonc** [comment] 2018-07-16 14:17
Assigned to @crwilcox at the behest of @JustinBeckwith

**Comment by lucasbrynte** [comment] 2018-09-20 12:47
I get the same behavior... Is it confirmed that this behavior is unintended? If it is intended - why?

Thanks

**Comment by busunkim96** [comment] 2018-12-03 18:32
@rohithmn3, @lucasbrynte 

It looks like this behavior is intended. The [documentation](https://cloud.google.com/iam/docs/understanding-roles#invitation_flow) says that it is not possible to grant he owner role through `gcloud`  or the Cloud IAM API. Owners can only be added through the GCP Console.

**Closed** 2018-12-03 18:33 UTC
Labels: priority: p2, status: blocked, type: question
