### ISSUE TITLE
Cloudidentity Batch Request Execute failure

### ISSUE THREAD

**Issue by kevinxu12** [googleapis/google-api-python-client#1268] opened 2021-03-24 21:00 UTC
I receive a `googleapiclient.errors.HttpError: <HttpError 404 when requesting https://cloudidentity.googleapis.com/batch returned "Not Found"> ` when attempting to run a cloudidentity batch execute. I believe this is a backend issue related to `https://cloudidentity.googleapis.com/batch` being a bad uri.

### Code Example
```
cloudidentity = build("cloudidentity", "v1", credentials=valid_credentials, cache_discovery=False)
batch_delete_devices = cloudidentity.new_batch_http_request(
            callback=handle_on_delete
)
device_id = sample_id
name=sample_name
batch_delete_devices.add(cloudidentity.devices().get(name=name), request_id=device_id)
batch_delete_devices.execute()

```
Executing the individual request without batching runs without issue.

#### Environment details

  - OS type and version: macOS Catalina 10.15.7
  - Python version: 3.8.2
  - pip version: 19.2.3
  - `google-api-python-client` version:  1.8.0

#### Stack trace
```
 python3.8/site-packages/googleapiclient/http.py", line 1515, in execute
    self._execute(http, self._order, self._requests)
  /python3.8/site-packages/googleapiclient/http.py", line 1449, in _execute
    raise HttpError(resp, content, uri=self._batch_uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://googleapis.com/batch/cloudidentity/v1 returned "Not Found">
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by parthea** [comment] 2021-08-09 15:55
I'm going to close this issue as obsolete as I believe the problem is already resolved. Please feel free to re-open this issue if you're still seeing the problem. 

If the issue still persists, please let me know the result after running the following command:
```
curl -i -X POST -H "Content-Type: multipart/mixed" -F "payload1={\"name\":\"payload1\"};type=application/json" -F "payload2={\"name\":\"payload2\"};type=application/json" https://cloudidentity.googleapis.com/batch -vvvv
```

**Closed by parthea** 2021-08-09 15:55 UTC
Labels: type: question
