### ISSUE TITLE
googleapiclient in python, using updateContact returns 403

### ISSUE THREAD

**Issue by RazHoshia** [googleapis/google-api-python-client#1169] opened 2021-01-22 18:24 UTC
Hi, I'm trying to get a list of contacts from Google's API, and then update some of them. While running the `updateContact` function I get 403 error `Request person.etag is different than the current person.etag. Clear local cache and get the latest person."` every time.

#### Environment details
  Using Jupyter Notebook
  - OS type and version: ubuntu 18 (wsl)
  - Python version: Python 3.6.9
  - pip version: pip 9.0.1
  - google-api-python-client version: 1.12.8

#### Code example

Im reading the contact's etag using this code:
```
service = build('people', 'v1', credentials=creds)
results = service.people().connections().list(
        resourceName='people/me',
        pageSize=100,
        personFields='names,emailAddresses').execute()
connections = results.get('connections', [])
```
Then for each `contact` in the `connections`, Im trying yo change the contact givenName and familyName:
```
service.people().updateContact(resourceName="contact's resource name",
                              updatePersonFields="names",
                              body={
                                  "etag": "contact's etag",
                                  "names": [
                                    {
                                      "familyName": "new family name",
                                      "givenName": "new given name"
                                    }
                                  ]
                                }
                              ).execute()
```
The contact's `etag` and `resourceName` are taken from the connection's list response.<br>for example:
```
print(connections[0])
{'resourceName': 'people/<resource_number>',
 'etag': 'etag string',
 'names': [{'metadata': {'primary': True,
    'source': {'type': 'CONTACT', 'id': 'id number'}},
   'displayName': 'x',
   'familyName': 'x',
   'givenName': 'x',
   'displayNameLastFirst': 'x',
   'unstructuredName': 'x'}]}
```

#### Stack trace
```
~/.local/lib/python3.6/site-packages/googleapiclient/_helpers.py in positional_wrapper(*args, **kwargs)
    132                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    133                     logger.warning(message)
--> 134             return wrapped(*args, **kwargs)
    135 
    136         return positional_wrapper

~/.local/lib/python3.6/site-packages/googleapiclient/http.py in execute(self, http, num_retries)
    913             callback(resp)
    914         if resp.status >= 300:
--> 915             raise HttpError(resp, content, uri=self.uri)
    916         return self.postproc(resp, content)
    917 

HttpError: <HttpError 400 when requesting https://people.googleapis.com/v1/people/<number>:updateContact?updatePersonFields=names&alt=json returned "Request person.etag is different than the current person.etag. Clear local cache and get the latest person.". Details: "Request person.etag is different than the current person.etag. Clear local cache and get the latest person.">

```

**Comment by parthea** [comment] 2021-01-25 12:43
Hi @RazHoshia,

Thanks for including sample code. Using the same code, I was able to update the `familyName` and `givenName` of a contact with family name `'bob'`. I've included the full code that I tried below. If you're still having trouble, please open an issue for the upstream People API by following the instructions on the support page [here](https://developers.google.com/people/support). Since sample code is working as intended, I'm going to close this off as there isn't anything further we can improve in the `google-api-python-client` client library. 

```
from google_auth_oauthlib import flow
from googleapiclient.discovery import build

client_id = "<replace me>"
client_secret = "<replace me>"
scopes = ["https://www.googleapis.com/auth/contacts"]
client_config = {
    "installed": {
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://accounts.google.com/o/oauth2/token",
        "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob"],
        "client_id": client_id,
        "client_secret": client_secret
    }
}

app_flow = flow.InstalledAppFlow.from_client_config(
    client_config, scopes=scopes
)

creds = app_flow.run_console()
service = build('people', 'v1', credentials=creds)
results = service.people().connections().list(
        resourceName='people/me',
        pageSize=100,
        personFields='names,emailAddresses').execute()
connections = results.get('connections', [])

for contact in connections:
  if contact["names"][0]["familyName"] == "bob":
      service.people().updateContact(resourceName=contact['resourceName'],
                                  updatePersonFields="names",
                                  body={
                                      "etag": contact["etag"],
                                      "names": [
                                        {
                                          "familyName": "new family name bob",
                                          "givenName": "new given name"
                                        }
                                      ]
                                    }
                                  ).execute()

```

**Closed by parthea** 2021-01-25 12:43 UTC
Labels: api: people, type: question
