### ISSUE TITLE
Each vault export write (ExportWritesPerMinutePerProject) quota is counted 10x

### ISSUE THREAD

**Issue by mngrant** [googleapis/google-api-python-client#1432] opened 2021-07-09 14:25 UTC
*Google Vault API issue tracker has [dismissed the issue](https://issuetracker.google.com/issues/192636545?pli=1), [2](https://issuetracker.google.com/issues/131206384), [3](https://issuetracker.google.com/issues/150278873), and most recently pointed toward python client as the issue (other users experience it Java, haven't test JS yet) and asked to open issue here.*

### Description 
**Every export appears to be counted 10 times toward the "Export Writes per minute" quota**

This is easily visualized on the GCP Project's Quota page. Reproducible when exporting with a SINGLE export.

### Requirements
- Python3
- Google SDK libraries installed via `pip` (Follow dev [Python QuickStart](https://developers.google.com/vault/quickstart/python) guide)
- Sample email account with data (empty/new accounts may not reproduce error)

### What steps will reproduce the problem?
1. Create new GCP Project
2. Use API tab and search library for "vault"
3. Enable - `https://console.cloud.google.com/apis/library/vault.googleapis.com` for project
4. Create OAuth Desktop client
5. Download json key and paste local path into script (line 11)
6. Run script: e.g. `python3 samplescript.py user.email@validdomain.com`
7. Observe error in exports (20 export limit reached after 2 exports)

### Expected
When exporting any fewer than 20 exports the RATE_LIMIT_EXCEEDED error should not be encountered. 

### SAMPLE CODE
Most of this is from Google's sample [Python Quickstart](https://developers.google.com/vault/quickstart/python) docs and [example export documentation](https://developers.google.com/vault/guides/exports)
```
from __future__ import print_function
import os.path, sys, time
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials

SCOPES = ['https://www.googleapis.com/auth/ediscovery']

# Path to local OAuth 2 client id file (create with "Desktop" type)
oauth_2_client_id_file = '/Users/grantgriffith/Downloads/client_secret_########.json'

def create_matter(service, email_address):
  matter_content = {
      'name': '{} - {} - DEV_TEST'.format(str(email_address),time.asctime())
  }
  matter = service.matters().create(body=matter_content).execute()
  return matter

def create_mail_account_held_data_export(service, export_name, matter_id, email_to_search):
    mail_query = {
      'corpus': 'MAIL',
      'dataScope': 'ALL_DATA',
      'searchMethod': 'ACCOUNT',
      'accountInfo': {
          'emails': [email_to_search]
      },
      "startTime": "2021-04-01T14:04:41Z", # Optional, limits export size
      "endTime": "2021-05-01T14:04:41Z", # Optional, limits export size
    }
    mail_export_options = {
        'exportFormat': 'MBOX',
        'showConfidentialModeContent': True
        }
    wanted_export = {
        'name': export_name + " MAIL Export",
        'query': mail_query,
        'exportOptions': {
            'mailOptions': mail_export_options
            }
        }
    return service.matters().exports().create(
        matterId=matter_id, body=wanted_export).execute()
  
def main():
    creds = None
    # The file token.json stores the user's access and refresh tokens, and is
    # created automatically when the authorization flow completes for the first
    # time.
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    # If there are no (valid) credentials available, let the user log in.
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(
                oauth_2_client_id_file, SCOPES)
            creds = flow.run_local_server(port=0)
        # Save the credentials for the next run
        with open('token.json', 'w') as token:
            token.write(creds.to_json())

    vault_service = build('vault', 'v1', credentials=creds)

    #Create new test Google Vault Matter
    new_matter = create_matter(vault_service, sys.argv[1])
    print("{} - CREATED, Status - {}".format(new_matter['name'], new_matter['state']))

    id = new_matter['matterId']
    email = sys.argv[1]

    #Create 1st export
    mail_export = create_mail_account_held_data_export(vault_service, "FIRST", id, email)
    print(mail_export['name'], mail_export['status'])

    #Create 2nd export
    mail_export2 = create_mail_account_held_data_export(vault_service, "SECOND", id, email)
    print(mail_export2['name'], mail_export2['status'])

    #Create 3rd export
    mail_export3 = create_mail_account_held_data_export(vault_service, "THIRD", id, email)
    print(mail_export3['name'], mail_export3['status'])

    #Create 4th export
    mail_export4 = create_mail_account_held_data_export(vault_service, "FOURTH", id, email)
    print(mail_export4['name'], mail_export4['status'])

if __name__ == '__main__':
    main()
```

HTTP Error response from my new test project that reproduces the error:
```
googleapiclient.errors.HttpError: 
<HttpError 429 when requesting 
https://vault.googleapis.com/v1/matters/e67ac8b7-1e55-49b9-9d9f-ddefa8233fb7/exports?alt=json returned 
"Quota exceeded for quota metric 'Export Writes' and limit 'Export Writes per minute' of service 'vault.googleapis.com' for consumer 'project_number:721746368665'.". 
Details: 
"[
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "reason": "RATE_LIMIT_EXCEEDED",
    "domain": "googleapis.com",
    "metadata": {
      "service": "vault.googleapis.com",
      "consumer": "projects/721746368665",
      "quota_limit": "ExportWritesPerMinutePerProject",
      "quota_metric": "vault.googleapis.com/export_writes"
    }
  }
]">
```

**Comment by parthea** [comment] 2021-07-12 16:39
Hi @mngrant,

Please kindly let me know if you can re-create the problem using the 'Try this API' interface on [this page](https://developers.google.com/vault/reference/rest/v1/matters.exports/create).

Regretfully I'm not able to re-create the problem as I don't have `Vault` configured on my test accounts. When I try to run the sample I receive the error `googleapiclient.errors.HttpError: <HttpError 403 when requesting https://vault.googleapis.com/v1/matters?pageSize=10&alt=json returned "Customer does not have Vault installed.". Details: "Customer does not have Vault installed.">`. I understand that `Vault` installation requires a G Suite enterprise account, which I do not have.

I've filed an internal bug for the Vault team to investigate or provide guidance on how to troubleshoot further. Googlers see b/193419503.

In the meantime, if you have a support contract with Google, please [contact support](https://support.google.com/a/answer/1047213) to ensure a timely response.

**Comment by mngrant** [comment] 2021-07-12 16:53
No issue on the web tests. I have been able to verify that works. 

Though, the 'Try this API' tests don't appear to count anywhere toward my quotas - I might be missing the test project where that quota is counted. I can hammer on it repeatedly and it does not register on the projects I am inspecting.

I have opened a ticket with Workspace Support who indicated they offer no API support and suggested I follow up with the bug tracker (again), who then kicked me here.

**Comment by parthea** [comment] 2021-07-12 17:09
Thanks for confirming. It is strange that the `Try this API` page does not affect quota. If you are interested to troubleshoot further independently, you could try using `curl` to send the requests manually.  You can capture the specific http requests being sent by adding the following lines at the top of your python file. Please don't share the HTTP logs here as they contains sensitive authentication information. In can you are interested in experimenting further, you can see an example of a curl request in #1422 which includes authentication.
```
import httplib2
httplib2.debuglevel = 4
```

I'll monitor the internal bug that I filed and report back if there is any update.

**Comment by mngrant** [comment] 2021-07-12 17:28
Possibly worth noting. I did just push another test with the API Explorer. I was able to hit a quota on my 5th export. I see all 4 exports running, but the 5th gives this error:

```
{
  "error": {
    "code": 429,
    "message": "Quota exceeded for quota metric 'Export Writes' and limit 'Export Writes per minute' of service 'vault.googleapis.com' for consumer 'project_number:292824132082'.",
    "status": "RESOURCE_EXHAUSTED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "RATE_LIMIT_EXCEEDED",
        "domain": "googleapis.com",
        "metadata": {
          "quota_metric": "vault.googleapis.com/export_writes",
          "quota_limit": "ExportWritesPerMinutePerProject",
          "service": "vault.googleapis.com",
          "consumer": "projects/292824132082"
        }
      }
    ]
  }
}
```

**Comment by mngrant** [comment] 2021-07-12 20:01
@parthea I was able to increase the log output and immediately on the third export attempt the rate limit was hit as expected. A `429`, as experienced in the web api explorer test above. The web UI explorer took a 5 total tests with the same account and query I use below for this test to hit failure (4 appeared to run and export into my test Vault Matter, the `429` came on the 5th attempt in the API explorer).

Here is the output removing the header `send` body line and obfuscating the account I'm testing with and truncated for size. This test body documents the full query I'm using - pretty basic and copied from the sample code in my original post.

```
send: b'POST /v1/matters/###REMOVED LINE###
send: b'{"name": "SECOND MAIL Export", "query": {"corpus": "MAIL", "dataScope": "ALL_DATA", "searchMethod": "ACCOUNT", "accountInfo": {"emails": ["MYTESTEMAIL@MYDOMAIN.com"]}, "startTime": "2021-04-01T14:04:41Z", "endTime": "2021-05-01T14:04:41Z"}, "exportOptions": {"mailOptions": {"exportFormat": "MBOX", "showConfidentialModeContent": true}}}'
reply: 'HTTP/1.1 429 Too Many Requests\r\n'
header: Vary: Origin
header: Vary: X-Origin
header: Vary: Referer
header: Content-Type: application/json; charset=UTF-8
header: Content-Encoding: gzip
header: Date: Mon, 12 Jul 2021 19:50:00 GMT
header: Server: ESF
header: Cache-Control: private
```

**Comment by parthea** [comment] 2021-07-13 15:29
Thanks for trying the API explorer again. Since you're able to reproduce an issue with the web API explorer as well, I'd recommend to request to re-open https://issuetracker.google.com/issues/192636545 .

**Comment by parthea** [comment] 2021-07-13 15:57
Hi @mngrant, I've heard back from the API team. This is working as intended. Each call to [export.create](https://developers.google.com/vault/reference/rest/v1/matters.exports/create) costs as 10 towards your quota limit, whereas [export.get](https://developers.google.com/vault/reference/rest/v1/matters.exports/get) costs as 1 towards your quota limit. Please visit this page to [view your current quota](https://developers.google.com/vault/limits) and request an increase. Note that this quota is a per minute quota, and is different from the limit of 20 concurrent exports.

**Comment by parthea** [comment] 2021-07-13 16:00
I'm going to close this issue as "Working as Intended", but please feel free to re-open this issue if you have additional questions.

If you have specific questions about quotas, you can reach out to the API team directly via [this support page](https://developers.google.com/vault/support).

**Closed by parthea** 2021-07-13 16:00 UTC
Labels: external, priority: p2, type: bug
