### ISSUE TITLE
Closing discovery item fails with AttributeError: 'Http' object has no attribute 'http'

### ISSUE THREAD

**Issue by ghaithbilbeisi** [googleapis/google-api-python-client#1046] opened 2020-09-25 09:38 UTC
The following line fails, looking at httplib2 shouldn't this be `self._http.close()` instead?

https://github.com/googleapis/google-api-python-client/blob/2d076b87cff4029a243357dad19564767bbf8751/googleapiclient/discovery.py#L1335

**Comment by busunkim96** [comment] 2020-09-28 16:11
Hey @ghaithbilbeisi, could you show more of the stack trace?

From discussion in #1047 it looks like the issue is the low version of `httplib2`. I also see that this wouldn't work correctly if you were passing in your own `httplib2` object (in that case it should just be `self._http.close()`).

**Comment by ghaithbilbeisi** [comment] 2020-09-30 09:40
Hi @busunkim96 , I get this when running my unittest with the following:

```python
def test_build_drive(self):
    creds = utils.authenticate('client_id.json')
    drive = utils.build_drive(creds)
    self.assertIsNotNone(drive)
    if drive:
        drive.close()
```

Using the following authenticate and build_drive methods:
```python
def authenticate(secret):
    """ Returns an oauth credentials object using the given secret, or stored credentials if available. """
    SCOPES = 'https://www.googleapis.com/auth/drive.readonly'
    store = file.Storage('storage.json')
    creds = store.get()       
            
    if not creds or creds.invalid:
        flow = client.flow_from_clientsecrets(secret, SCOPES)
        creds = tools.run_flow(flow, store)
    
    return creds

def build_drive(creds):
    try:
        drive = discovery.build('drive', 'v3', credentials=creds)#http=creds.authorize(Http()))
    except:
        drive = None
    return drive
```

Running this with google-api-python-client 1.12.3, httplib2 0.18.1, and python 3.8.3 gives the following error:

```
Traceback (most recent call last):
  File "token_test.py", line 16, in test_build_drive
    drive.close()
  File "/Users/ghaithbilbeisi/miniconda3/lib/python3.8/site-packages/googleapiclient/discovery.py", line 1335, in close
    self._http.http.close()
AttributeError: 'Http' object has no attribute 'http'
```

**Comment by busunkim96** [comment] 2020-09-30 23:52
I think the proper fix for this is to add `close` to AuthorizedHttp. Opened https://github.com/googleapis/google-auth-library-python-httplib2/pull/14

**Comment by parthea** [comment] 2021-03-03 22:51
I'm going to close off this issue as google-auth-httplib2 [0.1.0 ](https://github.com/googleapis/google-auth-library-python-httplib2/releases/tag/v0.1.0) was released on Monday with the fix from https://github.com/googleapis/google-auth-library-python-httplib2/pull/14 . If you're still having trouble after updating google-auth-httplib2, please re-open this issue with more information.

**Comment by solzard** [comment] 2021-03-05 22:38
This simple code still raises the same error with latest packages (`google-auth-httplib2 0.1.0`, `httplib2 0.19.0`, `google-api-python-client 2.0.2`).
```python
from googleapiclient.discovery import build

yt = build("youtube", "v3", developerKey="MY_KEY")
yt.close()

```

```error
Traceback (most recent call last):
  File "test_code.py", line 4, in <module>
    yt.close()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/googleapiclient/discovery.py", line 1364, in close
    self._http.http.close()
AttributeError: 'Http' object has no attribute 'http'

Process finished with exit code 1
```

**Comment by busunkim96** [comment] 2021-03-05 22:55
I think https://github.com/googleapis/google-api-python-client/pull/1231/ will (finally) fix this. I'll circle back to it next week. Thanks for the report @solzard!

**Comment by niva83** [comment] 2021-04-07 07:29
@busunkim96 actually #1231 did not fixed the issue since I am still having it:
```
Traceback (most recent call last):
  File "./src/sheet2xls.py", line 20, in <module>
    sheet = sheet_obj.get(sheet_id)
  File "/home/runner/.local/lib/python3.8/site-packages/gsheets/api.py", line 141, in get
    return self[id***
  File "/home/runner/.local/lib/python3.8/site-packages/gsheets/api.py", line 121, in __getitem__
    response = backend.spreadsheet(self._sheets, id)
  File "/home/runner/.local/lib/python3.8/site-packages/gsheets/tools.py", line 39, in __get__
    result = instance.__dict__[self.__name__*** = self.fget(instance)
  File "/home/runner/.local/lib/python3.8/site-packages/gsheets/api.py", line 69, in _sheets
    return backend.build_service('sheets', credentials=self._creds,
  File "/home/runner/.local/lib/python3.8/site-packages/gsheets/backend.py", line 34, in build_service
    return apiclient.discovery.build(**kwargs)
  File "/home/runner/.local/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/runner/.local/lib/python3.8/site-packages/googleapiclient/discovery.py", line 324, in build
    discovery_http.close()
AttributeError: 'Http' object has no attribute 'close'
##[error***Process completed with exit code 1.
```

from `pip list`:

google-api-core          1.26.3              
google-api-python-client 2.1.0               
google-auth              1.28.0              
google-auth-httplib2     0.1.0               
googleapis-common-protos 1.53.0   
httplib2                 0.19.1

**Comment by busunkim96** [comment] 2021-04-07 15:39
@niva83 I'm not able to reproduce the error you're seeing. Could you share the bit of your code that calls `discovery.build`?

```py
from googleapiclient import discovery


service = discovery.build("cloudasset", "v1")

service.close()
```

The stack trace seems to suggest it's failing on closing `discovery_http`, which is just a plain `httplib2` object rather than one from `google_auth_httplib2`. https://github.com/googleapis/google-api-python-client/blob/a5d20813e8d7589b0cec030c149748e53ea555a5/googleapiclient/discovery.py#L324

Could you try this code to see if you can close a plain `httplib2.Http` instance? If this doesn't work, the version of httplib2 you have installed may be too old.

```py
import httplib2


http = httplib2.Http()

http.close()
```

**Comment by niva83** [comment] 2021-04-07 16:27
@busunkim96 thanks, I will test this week and let you know how it goes.

**Comment by parthea** [comment] 2021-04-14 18:36
Hi @niva83 , I'm going to close this off as guidance has been provided in https://github.com/googleapis/google-api-python-client/issues/1046#issuecomment-815016260. If you're still having trouble, please re-open it with more information.

**Closed by parthea** 2021-04-14 18:36 UTC
Labels: :rotating_light:, priority: p2, type: question

**Comment by wescpy** [comment] 2025-05-31 21:14
This bug should be reopened for Python 2 users as the fix has not yet been backported to a v1 release of the client library. Since I can't reopen this issue for Python 2, I had to file [this new bug](https://github.com/googleapis/google-api-python-client/issues/2610) as a proxy.
