### ISSUE TITLE
Support for setting IAM Service Account Key expiration date

### ISSUE THREAD

**Issue by stdin** [googleapis/google-api-python-client#1267] opened 2021-03-24 20:35 UTC
Hello!

We want to set an expiration date ([validBeforeTime](https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery_cache/documents/iam.v1.json#L2614) field) when creating a new IAM service account key.

I've looked through the [method definition](https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery_cache/documents/iam.v1.json#L1433), but it only has the `name` parameter specified for the `create` method, and there is no separate `update` method for this resource type.

**Comment by parthea** [comment] 2021-03-29 12:02
Hi @stdin,

I followed the instructions [here](https://cloud.google.com/iam/docs/creating-managing-service-account-keys#iam-service-account-keys-create-rest) to create a service account and I can confirm that I am not able to set `validBeforeTime` at time of creation of the IAM Service Account Key. I am also unable to update the `validBeforeTime` as you indicated.

Steps to reproduce:
1) **Create a service account**
 Use the 'Try this API' section on [this page](https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts/create) to create a service account. 
Request Parameters:
name : `projects/<unique project id>`

Request Body:
```
{
  "accountId": "<unique project id>",
  "serviceAccount": {
    "displayName": "Test service account",
    "description": "My test service account"
  }
}
```

2) **Create a service account key**
Use the 'Try this API' section on [this page](https://cloud.google.com/iam/docs/reference/rest/v1/projects.serviceAccounts.keys/create) to create a service account key.
Request Parameters:
name : <Use the name from the response in step 1>
```
{
  "keyAlgorithm": "KEY_ALG_RSA_2048",
  "privateKeyType": "TYPE_GOOGLE_CREDENTIALS_FILE",
  "validBeforeTime": "2030-05-15T18:58:13Z"
}
```
I get the following response
```
{
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"validBeforeTime\": Cannot find field.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Invalid JSON payload received. Unknown name \"validBeforeTime\": Cannot find field."
          }
        ]
      }
    ]
  }
}
```

As a next step, please file an issue on this [support page](https://cloud.google.com/support-hub). If you have a support contract with Google, please create an issue in the support console to ensure a timely response.

Please also comment on the existing issue [here](http://issuetracker.google.com/issues/67747132) to get a status update. I've also updated the internal ticket to increase visibility of this feature request. Googlers see b/67773078. I'm going to close this issue since it is a feature request for the API rather than the python client library in this Github repo.

**Closed by parthea** 2021-03-29 12:02 UTC
Labels: api: iam, type: question
