### ISSUE TITLE
Getting past calendar events instead of future

### ISSUE THREAD

**Issue by DaniyalDhz** [googleapis/google-api-python-client#1055] opened 2020-10-03 19:02 UTC
If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: WIndows 10
  - Python version: `python 3.8.3`
  - pip version: `pip --version 20.2.3`
  - `google-api-python-client` version: `pip show google-api-python-client`

#### Steps to reproduce
Hi there!
Quick ques:
per google code snippet:
I am not sure if this is a bug or a feature to be added request, but I am trying to get all the calendar events in the past day, week, month. The only thing I could come up with was 
```
.
.
  now = dt.datetime.utcnow().isoformat() + 'Z' # 'Z' indicates UTC time
  Yes = '2020-10-02T18:12:08.853607Z'
  print('Getting the upcoming 10 events')
  events_result = service.events().list(calendarId='primary', timeMin=Yes, timeMax = now
                                      ,singleEvents=True,
                                      orderBy='updated').execute()

```
However, I didn't end up getting any results despite having events on my calendar in the past day.

Thanks!

**Comment by busunkim96** [comment] 2020-10-05 14:55
Hi,

Could you try a similar request via "Try this API" https://developers.google.com/calendar/v3/reference/events/list? If you get similar results (no events) the issue is likely in the API itself rather than in the library. In that case please use one of the [Calendar API support channels](https://developers.google.com/calendar/support).

**Comment by danieldhz** [comment] 2020-10-05 19:39
Hi @busunkim96 
It did work. However, the result is still very random and misleading. 
Example:
![image](https://user-images.githubusercontent.com/58639693/95122680-de9a4e80-071e-11eb-8e67-313ec0bfd0db.png)
As you can see, I have "google resume" & "reading" on October 3rd. On the contrary, JSON says I only have an event called "case" on October 3rd which is definitely not the case. 
```
  {
   "kind": "calendar#event",
   "etag": "\"32...0\"",
   "id": "23djv...3qp6n8c",
   "status": "confirmed",
   "htmlLink": "https://www.google.com/calendar/event?eid=MjNkan...aGxlaEBt",
   "created": "2020-10-03T17:46:23.000Z",
   "updated": "2020-10-03T17:46:23.942Z",
   "summary": "Case",
   "creator": {
    "email": "daniyaldehleh@gmail.com",
    "self": true
```

As well as, if singleEvent is True, it would still return recurring events right?

**Comment by parthea** [comment] 2020-12-07 01:33
I'm sorry that it took a while to respond to your last question. My understanding from the [Events: list](https://developers.google.com/calendar/v3/reference/events/list) documentation is that `singleEvents=True` will expand a recurring event into instances, so you should see the event which is recurring. From the screenshot it looks the 2 events are different colours which may indicate that you have multiple calendars. When the `calendarId` is set to `primary`, you'll only see the calendar of the currently logged in user. If you want to see additional calendars, you'll need to set the `calendarId` to the `id` corresponding to the specific calendar. I'm going to close this issue as duplicate of #1086 as it is related. If you're still having trouble please re-open this issue with additional information.

**Closed by parthea** 2020-12-07 01:33 UTC
Labels: api: calendar, type: question
