### ISSUE TITLE
"Bad request" when trying to make file on shared drive viewable by anyone

### ISSUE THREAD

**Issue by heiko-r** [googleapis/google-api-python-client#895] opened 2020-05-08 13:41 UTC
I need to change the permissions of a file on a shared drive to be viewable by "Anyone with the link".

### What works
* Changing the permissions in the Drive web UI
* Sharing the file with a specific user via v3 API:
  ```python
  drive_service_v3.permissions().create(fileId=file.get("id"), body={"role":"reader", "type":"user", "emailAddress": "example@gmail.com"}, supportsAllDrives=True).execute()
  ```

### What does not work
* Making the file publicly viewable via v3 API:
  ```python
  drive_service_v3.permissions().create(fileId=file.get("id"), body={"role":"reader", "type":"anyone"}, supportsAllDrives=True).execute()
  ```
  fails with
  ```
  HttpError: <HttpError 400 when requesting https://www.googleapis.com/drive/v3/files/1lGeZYluZ2a_qiCpfdIuvxMlQOk5VBVtL/permissions?supportsAllDrives=true&amp;alt=json returned "Bad Request. User message: """>
  ```
* Doing the equivalent via v2 API:
  ```python
  drive_service_v2.permissions().insert(fileId=file.get("id"), body={"role":"reader", "type":"anyone", "value": "anyone"}, supportsAllDrives=True, fields='id').execute()
  ```
  fails with
  ```
  <HttpError 400 when requesting https://www.googleapis.com/drive/v2/files/1lGeZYluZ2a_qiCpfdIuvxMlQOk5VBVtL/permissions?supportsAllDrives=true&amp;fields=id&amp;alt=json returned "Bad Request. User message: """>
  ```

I spent more than half the day on this, but couldn't find any working example on the internet, let alone in the official docs. What am I doing wrong here?

**Comment by busunkim96** [comment] 2020-05-12 00:47
Hi @heiko-r,

It is most likely unrelated to the issue at hand, but it looks like `supportsAllDrives` is now deprecated.

Would you mind trying this request using API Explorer? ("Try it!"  on the right side of [this page](https://developers.google.com/drive/api/v3/reference/permissions/create)) It will help narrow down if the issue is with the library or the underlying API.

**Comment by heiko-r** [comment] 2020-05-13 09:38
Thanks @busunkim96 !

The API Explorer (why didn't I think of this before?) also failed, but the error message there was a bit more verbose:
```json
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalidLinkVisibility",
    "message": "Bad Request. User message: \"\""
   }
  ],
  "code": 400,
  "message": "Bad Request. User message: \"\""
 }
}
```
So I found this [PHP specific solution](https://stackoverflow.com/questions/52781564/google-drive-api-team-drive-file-permissions-in-php-to-anyone-or-specific-doma) that set me off on the right track:

1. Use the [API explorer for Permissions: list](https://developers.google.com/drive/api/v3/reference/permissions/list) to find the ID of the conflicting permission (appears to have role=reader, type=domain and an ID ending in k). I didn't dive in deep enough to check if there's always only one of those, so that this could be automated in Python. But this permission ID appears to be the same for all files on a shared drive.
2. Delete this permission:
   ```python
   drive_service.permissions().delete(fileId=file.get("id"), permissionId='14641914808286825725k', supportsAllDrives=True).execute()
   ```
3. Create the new permission:
   ```python
   drive_service.permissions().create(fileId=file.get("id"), body={"role":"reader", "type":"anyone"}, supportsAllDrives=True).execute()
   ```

So my main issue is not with the library after all. But I have two suggestions:

- Should this possibility of conflicting permissions be added to the docs?
- Could the exceptions thrown by the library include more information, especially the 'reason' (see above)?

Btw., without the `suportsAllDrives`, I get a file not found error, and the docs say we need to keep using this option till 1st June 2020.

**Comment by parthea** [comment] 2020-12-13 02:59
Hi @heiko-r,

We've recently improved support for `error_details` in this library. I'm going to close this issue but please re-open it if you think there is more we can do to improve the experience in this library.

**Closed by parthea** 2020-12-13 02:59 UTC
Labels: api: drive, type: question
