### ISSUE TITLE
<HttpError 404 when requesting https://www.googleapis.com/drive/v2/files/1CwhDy8SBXaInfY2WdWfgK1wROeUNuesC?alt=json returned "File not found: 1CwhDy8SBXaInfY2WdWfgK1wROeUNuesC">

### ISSUE THREAD

**Issue by bc060400164** [googleapis/google-api-python-client#1186] opened 2021-02-17 10:38 UTC
After some  days i start getting the error. To solve the issue i need the other Gmail account. Why its happening? Any comment or guideline. File is there in drive with same link. After one week it starts giving the error.

**Comment by parthea** [comment] 2021-02-17 11:48
Hi @bc060400164 ,

Please can you share some sample code to see if this issue can be reproduced? As we haven't released a new version of this client library recently, my initial thought is that you may need to file a bug directly with the upstream API [using these steps](https://developers.google.com/drive/api/v3/support).

**Comment by bc060400164** [comment] 2021-02-18 06:56
Dear parthea 
This is the sample code and the error is uploaded, if I use the new google account it will work for one week approx and after that error will reproduce. i tried on two to three google accounts.: 

![error](https://user-images.githubusercontent.com/54372454/108317454-5bf6c500-71cf-11eb-83d5-5f41803340f0.JPG)

file_id = '1CwhDy8SBXaInfY2WdWfgK1wROeUNuesC'
downloaded = drive.CreateFile({'id': file_id})
downloaded = drive.CreateFile({'id':'1CwhDy8SBXaInfY2WdWfgK1wROeUNuesC'}) # replace the id with id of file you want to access
downloaded.GetContentFile('cherat-final-dataset.csv')  
 
# Read file as panda dataframe
import pandas as pd

**Comment by Squirrel623** [comment] 2021-04-20 20:35
I'm having a similar issue and I suspect it is an issue on Google's side but I haven't figured out anything yet.

I have a Google Cloud Platform service account with domain-wide delegation enabled and `https://www.googleapis.com/auth/drive` scope. 

Until recently the server using this account has not had any problems connecting to three different shared drives, creating folders underneath them, or returning a folder's contents. 

Now, the server is getting 404s when trying to create folders underneath a drive or list a directory's contents under the drive. The drive and those folders definitely exist - I can access them on the Google Drive web page. That leads me to believe this is a permissions issue but I have not found anything on my search.

This is the code for creating a folder underneath a drive that now returns a 404 and tells me the drive does not exist:
```python
file_metadata = {
    'name':  name,
    'mimeType': 'application/vnd.google-apps.folder',
    'parents': [drive_id]
}

file = service.files().create(body=file_metadata, fields='id', supportsAllDrives=True).execute()
```

I'm not sure exactly when this started happening but it was brought to my attention in the past few weeks. I don't think there is anything that this package can do to help out because it is just forwarding on Google's response but maybe someone can point us in the right direction.

**Comment by Squirrel623** [comment] 2021-04-21 16:47
I ended up figuring out my issue: https://stackoverflow.com/a/67199941/5404586

**Comment by parthea** [comment] 2021-08-09 21:11
I'm going to close this issue as obsolete but please feel free to re-open it if the issue still exists.

**Closed by parthea** 2021-08-09 21:11 UTC
Labels: type: question, needs more info, api: drive

**Comment by ManuelElizaldi** [comment] 2024-05-16 17:47
Hello! Was there any solution to this issue? 

I am currently running into a problem where my service account has access to a shared drive, I can get a list of the contents, but when I try to copy a file inside said folder I get the following error:

`HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v3/files/1Gj3CrJJkIPu08RlXR2nsSfNpNshYdRzyu73GX-J50QM?alt=json returned "File not found: 1Gj3CrJJkIPu08RlXR2nsSfNpNshYdRzyu73GX-J50QM.". Details: "[{'message': 'File not found: 1Gj3CrJJkIPu08RlXR2nsSfNpNshYdRzyu73GX-J50QM.', 'domain': 'global', 'reason': 'notFound', 'location': 'fileId', 'locationType': 'parameter'}]">`


I know the file exists since when I do :

`# recreate the .list() method to .copy() maybe? with the file id that I have 
response = service.files().list(q = query, fields = "files(id, name)", includeItemsFromAllDrives = True, supportsAllDrives = True).execute()
files = response.get('files', [])`

I indeed get a list of files. Using the output from this I tried making a copy of a file to no avail:

`# ID of the folder where you want the copy
folder_id = '1nUmm845UJF6vbMhUjq_r5CVvEjOUktAf'

# ID of the file you want to copy
original_id = '1Gj3CrJJkIPu08RlXR2nsSfNpNshYdRzyu73GX-J50QM'

# Name of the copy
copy_name = 'copy'

# New file metadata
new_file = {'name': copy_name, 'parents': [folder_id]}

# Copy the file
copied_file = service.files().copy(fileId=original_id, body=new_file).execute()

# Get the ID of the copied file
copied_file_id = copied_file['id']`


any help will be greatly appreciated!

**Comment by swb-buildarchetype** [comment] 2024-11-15 20:55
I am also trying to figure this out. Any ideas?
