### ISSUE TITLE
Authorization for Content API for Shopping

### ISSUE THREAD

**Issue by smartfin** [googleapis/google-api-python-client#313] opened 2016-11-28 18:22 UTC
Hi.

I'm trying to build script, that would every 24 hours pull data from Content API for Shopping and update some tables on own server.

But I faced up with auth problem. 
I moved through steps in guide, created client id, and even recieved refresh token via `--noauth_local_webserver` option.

But this token became invalid in few hours and require client to interact with app again.

I have same script, but for Google Adwords Api. In that case my refresh_token lives much longer, as for now - few months.

Can you please point me, where I'm doing something wrong. Thanks.

**Comment by jonparrott** [comment] 2016-11-28 19:01
This seems like more of an issue for oauth2client, but we're also the maintainers of that library.

There are two token you can acquire with OAuth 2: an access token which is short lived (1 hour) and a refresh token that can be used to acquire a new access token without prompting the user.

Can you share the code you're using to do authentication? It's likely you just need to add another parameter to acquire the refresh token.

**Comment by smartfin** [comment] 2016-11-29 21:05
Thanks for your response.

Basically, I'm reproducing it on examples from [https://github.com/smartfin/googleads-shopping-samples/tree/master/python](https://github.com/smartfin/googleads-shopping-samples/tree/master/python)

I cloned repository and created `content-oauth2.json` with credentials.

After first use `products_list.py` I got link to navigate via browser and get refresh token. After that, I can see list of products. But in few hours, I have message 

> The credentials have been revoked or expired, please re-run the application to re-authorize

**Comment by prakashkumar-git** [comment] 2016-12-14 14:42
I am also facing the same issue
The credentials have been revoked or expired, please re-run the application to re-authorize

Help please

**Comment by jonparrott** [comment] 2016-12-14 17:46
@smartfin @prakashkumar-git  it's difficult to know what's going on because there's a lot of code in those samples. You could try reaching out to smartfin on that github repo and seeing if their auth code is perhaps preventing the refresh cycle from working?

**Comment by prakashkumar-git** [comment] 2016-12-14 19:08
Hi  jon , i have try to debug,
the problem is at L66,

https://github.com/smartfin/googleads-shopping-samples/blob/master/python/auth.py#L66
`    if credentials is not None and not credentials.invalid:
      return credentials`

This part stop working, so each time i have comment and comment it .

If possible, Kindly review that why **credentials.invalid** is not doing what is suppose to do.


For now , the temporary is to comment  this part when every we are facing this issue and allow to re authenticate..

**Comment by tejastank** [comment] 2017-08-25 09:06
Same issue:

with django use google analutics API.

In localhost working all fine, ask for google permission to access "google analytics" permission in automatically in browser new tab.

But same code I put on server it give me below message.

 

> Your browser has been opened to visit:
> 
>     https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fanalytics.readonly&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&response_type=code&client_id=1071534795399-9q9urdlq845cu060e7isa56usjsdnu3o.apps.googleusercontent.com&access_type=offline
> 
> If your browser is on a different machine then exit and re-run this
> application with the command-line parameter
> 
>   --noauth_local_webserver

What should I had to do ?


  

>   parser = argparse.ArgumentParser('project-id-xxxx-xxxx --noauth_local_webserver',
>                     formatter_class=argparse.RawDescriptionHelpFormatter,
>                     parents=[tools.argparser],add_help=False)
>     flags = parser.parse_args([])
> 
>     flow = client.flow_from_clientsecrets('client_secret_1xxxxxxxx-xxx.apps.googleusercontent.com.json',
>                     scope='https://www.googleapis.com/auth/analytics.readonly',
>                     redirect_uri='urn:ietf:wg:oauth:2.0:oob')
> 
>     storage = file.Storage('analytics_%s'%request.user.id + '.dat')
>     credentials = storage.get()
>     if credentials is None or credentials.invalid:
>         credentials = tools.run_flow(flow, storage, flags)  


To short out issue on server, what should I had to do ??

**Comment by mcdonc** [comment] 2018-07-24 14:49
I think this issue may need closing, for better or worse.  Rationale: it has been many months since a post that isn't a "+1" or "me too" style, and a coherent set of steps to reproduce never appeared here.  I'm going to leave it open with a "needs more info" tag for a bit; if someone can boil this down to a set of steps to reproduce that includes code, please comment here and I'll follow up.  If we can't get that, I'll likely close it shortly.

**Closed** 2018-12-12 23:49 UTC
Labels: :rotating_light:, needs more info, priority: p2, type: bug
