### ISSUE TITLE
Content API Discrepency - update() is not an available method

### ISSUE THREAD

**Issue by Syntaf** [googleapis/google-api-python-client#1467] opened 2021-07-27 23:41 UTC
It seems that the documentation references a method not available on the products resource. Our team is really hoping there's a way to partially update resources even with this method missing, as `insert()` seems to always overwrite the entire product representation.

#### Environment details

  - OS type and version: 
  - Python version: `3.6.12`
  - pip version: `20.3.3`
  - `google-api-python-client` version: 
     ```
     Name: google-api-python-client
     Version: 2.3.0
     Summary: Google API Client Library for Python
     Home-page: https://github.com/googleapis/google-api-python-client/
     Author: Google LLC
     Author-email: googleapis-packages@google.com
     License: Apache 2.0
     Location: /usr/local/lib/python3.6/site-packages
     Requires: httplib2, google-auth-httplib2, google-auth, six, uritemplate, google-api-core
     Required-by: pygsheets
     ```

#### Steps to reproduce

  1. Instantiate a content API client with the most recent version
  2. Attempt to fetch the `products().update` attribute as defined in the [documentation](https://googleapis.github.io/google-api-python-client/docs/dyn/content_v2_1.products.html)

#### Code example

```python
     >>> client = discovery.build('content', 'v2.1', credentials=<credentials>)
     >>> client.products().update
     Traceback (most recent call last):
       File "<console>", line 1, in <module>
     AttributeError: 'Resource' object has no attribute 'update'
```

#### Stack trace
```
     Traceback (most recent call last):
       File "<console>", line 1, in <module>
     AttributeError: 'Resource' object has no attribute 'update'
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by parthea** [comment] 2021-07-30 11:07
Hi @Syntaf,

I'm able to see the `<client>.products().update()` instance method for this client. Please note that `update()` is an instance method not an `attribute`.

```
>>> from googleapiclient.discovery import build
>>> client = build('content', 'v2.1')
>>> client.products().update()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/partheniou/git/google-api-python-client-upstream/googleapiclient/discovery.py", line 1012, in method
    raise TypeError('Missing required parameter "%s"' % name)
TypeError: Missing required parameter "merchantId"
```

**Comment by Syntaf** [comment] 2021-07-30 17:01
@parthea Interesting, thanks for replying and confirming it does indeed exist. Do you have a different package version than what I posted above?

```
>>> client = discovery.build('content', 'v2.1', credentials=credentials)
>>> client.products().insert
<bound method createMethod.<locals>.method of <googleapiclient.discovery.Resource object at 0x7f6c1d08d3c8>>
>>> client.products().update
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Resource' object has no attribute 'update'
```

**Comment by parthea** [comment] 2021-08-10 17:30
I'm going to close this issue as I'm not able to reproduce the issue but please feel free to re-open it.

**Closed by parthea** 2021-08-10 17:30 UTC
Labels: type: question
