### ISSUE TITLE
Add a copy of each discovery doc for libraries to fall back to

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-api-python-client#962] opened 2020-07-08 01:54 UTC
This is similar to what NodeJS does, and helps reduce the impact of a discovery doc being temporarily unavailable https://github.com/googleapis/google-api-python-client/issues/959.

Note that we will need some sensible cadence for re-publishing the library with the new discovery docs.

**Comment by parthea** [comment] 2020-12-07 18:34
Closing as duplicate of #1063

**Closed by parthea** 2020-12-07 18:34 UTC
Labels: type: feature request
