### ISSUE TITLE
Pagination in Remarketing Lists

### ISSUE THREAD

**Issue by JudeDMello** [googleapis/google-api-python-client#758] opened 2019-09-17 14:20 UTC
Hi,

https://developers.google.com/resources/api-libraries/documentation/dfareporting/v3.3/python/latest/dfareporting_v3.3.remarketingLists.html

This is the code which we were 
```python
service = discovery.build('dfareporting', 'v3.3', credentials=credentials)

try:
    # Construct the request.
    request = service.remarketingLists().list(profileId=profile_id, advertiserId=advertiser_id, floodlightActivityId=floodlightActivityId, name='to')
    df3 = pd.DataFrame({'id': [], 'name': []})
    while True:
        response = request.execute()
        for remarketing_list in response['remarketingLists']:
            df3 = df3.append({'id': remarketing_list['id'], 'name': remarketing_list['name']}, ignore_index=True)


        print(response)

        if response['remarketingLists'] and response['nextPageToken']:
            request = service.remarketingLists().list_next(request,response)

        else:
            break

except client.AccessTokenRefreshError:
    print ('The credentials have been revoked or expired, please re-run the '
           'application to re-authorize')
```

We were trying to pull remarketing data on a client. The code works fine for the first page, but when we try to pull for the next one, the response is as below, which seems to suggest that the app isn't able to paginate.

```
Response --> 'kind': 'dfareporting#remarketingListsListResponse', 'remarketingLists': []
```
However, pagination works perfectly when tested with Google API Explorer.  Please advise.

-Jude D'Mello

**Comment by busunkim96** [comment] 2019-09-17 16:49
Code above seems to be pulled from this sample: https://github.com/googleads/googleads-dfa-reporting-samples/blob/master/python/v3_3/get_remarketing_lists.py

**Comment by SurferJeffAtGoogle** [comment] 2020-04-23 18:46
@jimper 
I don't have the necessary accounts and permissions to reproduce this issue.  Could you debug?

**Comment by jimper** [comment] 2020-04-27 04:31
I can verify that paging through remarketingLists with the sample worked as expected using a test account. So this doesn't seem like a library issue to me, but there could still be an issue on the DCM side. Unfortunately there isn't enough info in the original report to reproduce exactly.

If you're still running into issues with this, I recommend reaching out to [DCM API support](https://developers.google.com/doubleclick-advertisers/get-support) and providing the specific values you used when making the request: user profile ID, advertiser ID, floodlight activity ID. The support team has the permissions necessary to reproduce and debug further.

**Comment by danoscarmike** [comment] 2020-05-15 03:49
@JudeDMello hope you have been able to get support from DCM side. I'm going to close this one out now as we are reasonably confident the issue is not in the library. Please feel free to continue the discussion here and we can reopen if something new comes up.

**Closed by danoscarmike** 2020-05-15 03:49 UTC
Labels: :rotating_light:, priority: p2, type: bug
