### ISSUE TITLE
Updated

### ISSUE THREAD

**Issue by lamjay007** [googleapis/google-api-python-client#879] opened 2020-04-21 19:59 UTC
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

**Comment by busunkim96** [comment] 2020-04-22 16:37
Hi @lamjay007, I'm going to close this issue as it's unclear to me what the problem is. Feel free to open another issue with more details.

Thanks!

**Closed by busunkim96** 2020-04-22 16:37 UTC
Labels: triage me
