### ISSUE TITLE
Published package is missing discovery files in discovery_cache

### ISSUE THREAD

**Issue by busunkim96** [googleapis/google-api-python-client#1214] opened 2021-03-04 01:06 UTC
Many thanks to the @wyk9787 for noticing this and reaching out.

All calls to `discovery.build()` using `2.0.0` fail with "unknown api name or version".

```python
from googleapiclient import discovery

client = discovery.build("cloudprofiler", "v2")
```

This is because the published package has no `discovery_cache/documents` directory. 

1. `python3 -m venv env`
2. `source env/bin/activate`
3. `python3 -m pip install google-api-python-client`
4. `ls env/lib/python*/site-packages/googleapiclient/discovery_cache`

```
busunkim@busunkim:~/github$ ls env/lib/python*/site-packages/googleapiclient/discovery_cache
appengine_memcache.py  base.py  file_cache.py  __init__.py  __pycache__
```

**Comment by parthea** [comment] 2021-03-04 16:26
Version 2.0.1 also has the same issue. The issue is resolved by changing this [line](https://github.com/googleapis/google-api-python-client/blob/master/setup.py#L63) from 
```
    package_data={},
```
to
```
package_data={"googleapiclient": ["discovery_cache/documents/*.json"]},
```

**Closed** 2021-03-04 17:02 UTC
Labels: priority: p1, type: bug

**Comment by chensun** [comment] 2021-03-05 07:01
@parthea, the issue still exists in 2.0.2 for me.

```
!pip freeze | grep google-api-python-client
google-api-python-client==2.0.2
```

and I got the same error:
```
/opt/conda/lib/python3.7/site-packages/googleapiclient/_helpers.py in positional_wrapper(*args, **kwargs)
    132                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    133                     logger.warning(message)
--> 134             return wrapped(*args, **kwargs)
    135 
    136         return positional_wrapper

/opt/conda/lib/python3.7/site-packages/googleapiclient/discovery.py in build(serviceName, version, http, discoveryServiceUrl, developerKey, model, requestBuilder, credentials, cache_discovery, cache, client_options, adc_cert_path, adc_key_path, num_retries, static_discovery)
    280                 developerKey,
    281                 num_retries=num_retries,
--> 282                 static_discovery=static_discovery,
    283             )
    284             service = build_from_document(

/opt/conda/lib/python3.7/site-packages/googleapiclient/discovery.py in _retrieve_discovery_doc(url, http, cache_discovery, serviceName, version, cache, developerKey, num_retries, static_discovery)
    385             return content
    386         else:
--> 387             raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
    388 
    389     actual_url = url
```

After I downgraded to 1.12.8, the error is gone.

**Comment by chensun** [comment] 2021-03-05 07:20
Okay, I just found out: https://github.com/googleapis/google-api-python-client/issues/1225#issuecomment-791058235

Our API is indeed private at this point.

**Comment by Ark-kun** [comment] 2021-03-08 22:10
> Okay, I just found out: [#1225 (comment)](https://github.com/googleapis/google-api-python-client/issues/1225#issuecomment-791058235) and [#1225 (comment)](https://github.com/googleapis/google-api-python-client/issues/1225#issuecomment-791045487)
> 
> Our API is indeed private at this point.

@chensun 
See the comment there: https://github.com/googleapis/google-api-python-client/issues/1225#issuecomment-793111851

**Comment by chensun** [comment] 2021-03-08 22:25
> @chensun
> See the comment there: [#1225 (comment)](https://github.com/googleapis/google-api-python-client/issues/1225#issuecomment-793111851)


Yes, I saw that, it's in the 2nd comments I referenced above. 

In the original comment, it says:
> This results in behavior equivalent to 1.x of this library.

So my thinking was why bother upgrading to 2.x, yet changing the code to make it behave just like 1.x. There's no known features from 2.x that we want to take advantage of at this moment. So why not just use 1.x until our API becomes public, by that time we can lift the version restriction without changing the code twice. WDYT? @Ark-kun

**Comment by parthea** [comment] 2021-03-09 14:02
I'm re-opening this issue to propose a change to improve the behaviour in version 2.0.2. By design, `google-api-python-client` version 2.0.2 will fail if the library doesn't have the service definition and `static_discovery=True`, however we may be able to make some improvements to the default value of `static_discovery` based on the arguments provided to `discovery.build()`.

The following sample code from #935 will result in a breaking change when upgrading to 2.0.2 if the discovery document is not public because the user has not specified `static_discovery`, and the default value is `True.
```
my_client = googleapiclient.discovery.build(
    'someapi',
    'v1alpha1',
    discoveryServiceUrl=apiclient.discovery.V2_DISCOVERY_URI + '&labels=TRUSTED_TESTER_FEATURE',
    developerKey=my_developer_key)
```

I'd like to propose to make the above code work. Looking at the above snippet, one can assume that the user wants to retrieve discovery documents dynamically since they have provided the `discoveryServiceUrl` argument. 

If a user specifies the `discoveryServiceUrl` argument in `discovery.build()` but does not specify the `static_discovery` argument, we should assume that the user wants to retrieve the discovery document from the internet. In that case, the default value for `static_discovery` would be `False`.

If we proceed, the docs would be updated to explain the new behaviour.

**Comment by parthea** [comment] 2021-03-09 14:03
cc @busunkim96 for review
