### ISSUE TITLE
Marshal/export feature

### ISSUE THREAD

**Issue by Jordan-Mesches** [googleapis/google-api-python-client#1178] opened 2021-02-08 21:35 UTC
I'm currently using AWS lambda, and I'm trying to use this library to interact with some gsuite products. So naturally I want to split up different parts of my project as to embrace micro service architecture that comes with lambda. So here comes my problem, I want to have a Authenticator lambda that can return Authentication to other lambdas, however when using `service_account_creds.with_subject(admin-email)` it returns a `google.oauth2.service_account.Credentials`object. Now this is great however I'm not able to return this in my lambda, and my attempts at marshaling it myself have failed. So it'd be great if their was a feature to either Marshall the object, or like export it to Json or something like that.

Also if does already exist sorry, I was unable to find it anywhere.

**Comment by busunkim96** [comment] 2021-02-09 15:44
Closing since this is a duplicate of the google-cloud-python issue.

**Closed by busunkim96** 2021-02-09 15:44 UTC
Labels: triage me
