### ISSUE TITLE
google-api-python-client does not honor `no_proxy` environment variable

### ISSUE THREAD

**Issue by MaT1g3R** [googleapis/google-api-python-client#726] opened 2019-07-24 16:08 UTC
#### Environment details

  - OS: Ubuntu 18.04
  - Python version: 3.6.8
  - pip version: 19.1.1
  - `google-api-python-client` version: 1.7.9

#### Steps to reproduce

We have a squid proxy running; The squid is not able to talk to google apis/metadata server.

```
export no_proxy=metadata.google.internal,.googleapis.com
export http_proxy=http://squid:3128
export https_proxy=http://squid:3128
```

We expect the `no_proxy` env var is honored.
This is an issue with [httplib2](https://github.com/httplib2/httplib2), we've already sent a PR to them here: https://github.com/httplib2/httplib2/pull/140

**Comment by temoto** [comment] 2019-07-27 16:03
Hello. Sorry, the problem was caused by my bad code. Fix is merged in httplib2 master.

**Comment by temoto** [comment] 2019-07-28 11:44
And now it's released as 0.13.1 on PyPI. Sorry for inconvenience.

**Comment by busunkim96** [comment] 2019-07-29 17:14
@temoto Thank you for the quick fix!

**Closed by busunkim96** 2019-07-29 17:14 UTC
Labels: external, priority: p2, type: bug

**Comment by temoto** [comment] 2019-07-29 18:01
Just to be clear: @MaT1g3R did all the work.

**Comment by busunkim96** [comment] 2019-07-29 18:15
Thank you @MaT1g3R! :tada:
