### ISSUE TITLE
Incorrect errors logged by the positional_decorator

### ISSUE THREAD

**Issue by hiranya911** [googleapis/google-api-python-client#825] opened 2020-02-18 22:27 UTC
Calling `http.BatchHttpRequest()` with only positional arguments raises/logs the following error:

```
req = BatchHttpRequest(callback, my_batch_uri)

TypeError: __init__() takes at most 1 positional argument (3 given)
```

This makes no sense since I'm only passing 2 arguments to the constructor.

Moreover, the decorator on the constructor indicates `positional(1)`, which I assume means should allow at most one positional argument. But the following doesn't work:

```
req = BatchHttpRequest(callback, batch_uri=my_batch_uri)

TypeError: __init__() takes at most 1 positional argument (2 given)
```

**Comment by busunkim96** [comment] 2020-02-20 18:13
It looks like that decorator was written to force arguments to be passed by name. The number '1' in `positional(1)` means 'allow 1 positional argument'. In this case the one allowed positional argument is `self`. Everything after it must be passed as a keyword.

https://github.com/googleapis/google-api-python-client/blob/66bb32cc70353296dbf1876ae8c22baf6562cfb9/googleapiclient/_helpers.py#L42-L110

Closing as this works as intended.

**Closed by busunkim96** 2020-02-20 18:13 UTC
Labels: triage me
